Repository MSK-Documents/msk-ui, pull requests merged in 2020-08, with the labels that each got.

#7 Add contact component
  src/modules/resume/contact/index.js
  src/modules/resume/contact/metadata.js
  src/modules/resume/contact/variants/basic/contributors.js
  src/modules/resume/contact/variants/basic/index.js
  src/modules/resume/contact/variants/basic/metadata.js
  src/modules/resume/contact/variants/basic/properties.js
  src/modules/resume/contact/variants/basic/render.js
  src/modules/resume/contact/variants/iconic/contributors.js
  src/modules/resume/contact/variants/iconic/index.js
  src/modules/resume/contact/variants/iconic/metadata.js
  src/modules/resume/contact/variants/iconic/properties.js
  src/modules/resume/contact/variants/iconic/render.js
  src/modules/resume/contact/variants/index.js
  src/modules/resume/index.js
Labels: enhancement

#27 🐛 checks for 'render' in undefined
  app/components/layout-area.js
Labels: bug

#28 Removed hooks dependency from 'Ribbon' resume cover
  src/modules/resume/cover/variants/ribbon/render.js
Labels: enhancement

#30 added basic business card template
  package.json
  src/modules/business-card/basic/index.js
  src/modules/business-card/basic/metadata.js
  src/modules/business-card/basic/variants/back side/contributors.js
  src/modules/business-card/basic/variants/back side/index.js
  src/modules/business-card/basic/variants/back side/metadata.js
  src/modules/business-card/basic/variants/back side/properties.js
  src/modules/business-card/basic/variants/back side/render.js
  src/modules/business-card/basic/variants/front side/contributors.js
  src/modules/business-card/basic/variants/front side/index.js
  src/modules/business-card/basic/variants/front side/metadata.js
  src/modules/business-card/basic/variants/front side/properties.js
  src/modules/business-card/basic/variants/front side/render.js
  src/modules/business-card/basic/variants/index.js
  src/modules/business-card/index.js
  src/modules/business-card/metadata.js
Labels: new-variant

#24 Added: Frame variant of cover in resume component
  public/Base64Icons.js
  src/modules/resume/cover/variants/frame/contributors.js
  src/modules/resume/cover/variants/frame/index.js
  src/modules/resume/cover/variants/frame/metadata.js
  src/modules/resume/cover/variants/frame/properties.js
  src/modules/resume/cover/variants/frame/render.js
  src/modules/resume/cover/variants/index.js
Labels: enhancement

#15 Added a 'Ribbon' style skill-set variant
  src/modules/resume/skill-set/variants/index.js
  src/modules/resume/skill-set/variants/ribbon/contributors.js
  src/modules/resume/skill-set/variants/ribbon/index.js
  src/modules/resume/skill-set/variants/ribbon/metadata.js
  src/modules/resume/skill-set/variants/ribbon/properties.js
  src/modules/resume/skill-set/variants/ribbon/render.js
Labels: new-variant

#18 Square variant for resume cover
  src/modules/resume/cover/variants/index.js
  src/modules/resume/cover/variants/square/contributors.js
  src/modules/resume/cover/variants/square/index.js
  src/modules/resume/cover/variants/square/metadata.js
  src/modules/resume/cover/variants/square/properties.js
  src/modules/resume/cover/variants/square/render.js
Labels: new-variant
